name: Run Selenium Tests v.1

on:
  push:
    branches:
      - main  # Запускать на пушах в ветку main
  pull_request:
    branches:
      - main  # Запускать на пулл-реквестах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu для запуска контейнера

    services:
      docker:
        image: docker:20.10.7  # Убедитесь, что Docker доступен в окружении
        options: --privileged  # Разрешить выполнение Docker внутри контейнеров

    steps:
    # Проверка кода из репозитория
    - name: Checkout repository
      uses: actions/checkout@v2

    # Установить Docker Buildx (позволяет кросс-платформенные сборки)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Логин в DockerHub (не обязательно, если вы собираете локально)
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка Docker-образа
    - name: Build the Docker image
      run: docker build -t selenium-tests .

    # Запуск тестов внутри Docker-контейнера
    - name: Run tests inside Docker container
      run: docker run selenium-tests
